<center> <h2> DS 3000 - Fall 2021</h2> </center>
<center> <h3> DS Report </h3> </center>

<center> <h3>Beat the Streak: Predicting Baseball Hits</h3> </center>
<center><h4>Melis Akinci, Kevin Schmitt, Rachel Rouff</h4></center>

<hr style="height:2px; border:none; color:black; background-color:black;">

#### Executive Summary:

Add your summary here (100-150 words)

Provide a brief summary of your project. After reading this executive summary, your readers should have a rough understanding of what you did in this project. You can think of this summary in terms of the four sections of the report and write 1-2 sentences describing each section.


## Introduction

Our project focuses on the MLB’s Beat The Streak game. It is a competition the MLB hosts each baseball season where participants are able to compete for the $5.6 million prize. Each day, participants select a player who they believe will get a hit in their game. The object of the game is to get a streak of 57 correct choices in order to beat Joe DiMaggio’s historic 56-game hitting streak. In addition to the prize, our project can be used to assist baseball coaches and general managers in producing the most effective lineup for their games in order to maximize the number of hits, thus increasing their chances of winning the game. 

## Method


### results

##discussin

<hr style="height:2px; border:none; color:black; background-color:black;">

## Outline
1. <a href='#1'>INTRODUCTION</a>
2. <a href='#2'>METHOD</a>
3. <a href='#3'>RESULTS</a>
4. <a href='#4'>DISCUSSION</a>

<a id="1"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 1. INTRODUCTION

<h4>Problem Statement</h4>

Each baseball season, the MLB hosts an online game called Beat The Streak in which participants select a player each day that they think will get a hit in their MLB game. The participant attempts “to establish a virtual ‘hitting streak’ and keep it going for as long as possible”(Beat the Streak Official Rules). If the player the participant chose gets a hit, their streak will continue, however, if they do not get a hit, the streak will go back down to zero. The goal is to get up to a streak of 57 days in order to beat Joe DiMaggio’s 56-game hitting streak. We want to create a program that will use the data on all players and games in the MLB in order to output a ranked list of the top 5 players that are most likely to get a hit on a given day with their calculated probability of getting a hit. 

<h4>Significance of the Problem</h4>

The winner of this competition wins $5.6 million, and no one has ever successfully completed the 57-day objective, so we want to use predictions based on the provided MLB data in order to try to beat the game. The insights from this problem could end up being a helpful and applicable tool for team managers in the MLB who are trying to choose which players to put in the lineup based on their probability of getting a hit in that game. Some previous work on this topic can be found on the following websites.
* https://math.stackexchange.com/questions/513627/baseball-batting-average-and-probability
* http://www.baseballmusings.com/

<h4>Questions</h4>

* Is it possible to effectively predict whether a player is going to get a hit in their game?
* Are there any consistent patterns or indicators of whether a player is going to get a hit?
* Which ML algorithm will be the most effective when it comes to predicting the hits.
* ***I AM HERE - -melis added some questinos above this***

* End this section with a list of data analysis questions you tackled in this project
* You should tie these questions to the problem statement and its significance
    * e.g. Given the aforementioned problem and its importance, we set out to tackle the following questions:
    
    * **Requirement:**
        * You should have at least one question tapping into the comparison of various machine learning algorithms (at least three) in predicting/classifying your target variable from your features variables.


### NOTE: PLEASE READ THIS SECTION


While this section provides bullet points as prompts, your Introduction should consist of coherent paragraphs. You are required delete all the prompts from this template, except for headings. Failing to do so will result in substantial point deductions.

<a id="2"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 2. METHOD

### 2.1. Data Acquisition

* Describe where you obtained your data. Provide a link to the original source. 
* If you scraped your data, include your code as a **separate** Notebook file.
* Your data should be stored in an online repository (e.g., GitHub) and your code should retrieve your data from that online resource. You can read csv files from the Web in the same way that you read files from local drive.

### i am assuming the 3 things above are done separately
* Describe the dataset (i.e., what it is about) and the number of variables/samples included.


Our dataset includes several statistical values of the players in individual games. While there are several different statistical values aside from the hit rate, these values are incredibly important to consider as they greatly affect the likelihood of a player getting a hit, especially the opponent’s pitcher’s statistics. We have over 11,000 sample rows. Our features include whether the game is a home game (Home?), the date the game took place (Date), the at bats v. pitcher that the hitter is facing in their overall career (ABVP), and the hits versus the pitcher they are facing in their overall career (HVP). Furthermore, we have more feature variables including the number of extra-base hits (XBH), the number of home runs (HR), the number of runners batted in (RBI), the number of walks (BB), average number of hits (AVG), and the on base percentage (OBP) which allow us to gain further insight into the statistics of the game. Using the feature variables, we have a target variable of the number of at bats (AB_actual), number of hits (H_actual), and the percentage of at bats that were hits (AVG_actual) which will be used to represent the likelihood of that player getting a hit.

### 2.2. Data Analysis
* Describe your predictive model in greater detail. What outcome variable are you going to predict from what feature variables? Why do you think those are important predictors?

*** didn't do the: describe your predictive model in greater detail***
The feature variables "home?", "ABVP", "HVP", "XBH". "HR", "RBI", "BB", and "AVG" will help predict the tow outcome variable "AB_actual", "H_actual", and "AVG_actual". These are important predictors because each of these elements are key to whether a player has a hit or not at a ceratin game. Many studies show that whether a player is at their home fields influences their ability to get a hit and their overall performance in a game. The pitcher along with their success against the batter does influence their ability to get a hit since many pitchers have varying styles. The number of home runs, extra base hits, and average number of hits are some of the best representations towards the general strength of the player and their ability to achieve a hit. Furthermore, the number of runners battled, number of walks, and on base percentage further allow us to gain more detail on how effective each player is. 

* Describe why this is a supervised ML problem and identify the sub-category of the learning task (e.g. classification).

Our project is tackling a regression problem as it is trying to predict the expected average of a player in a given game (hits / at-bats). We considered using a classification algorithm and classifying based on hit or no-hit, but chose the regression approach as a higher predicted average would mean a higher chance of getting at least one hit and we felt this was more specific than a yes or no classification.

* What machine learning algorithms are you going to use? **Why?** You should list at least three algorithms. Provide a brief description of each algorithm and explain why you think they are appropriate for your data.

## not sure if this is still accurate --> need to update

We are going to try all of the main regression algorithms we have covered in class so far (Linear Regression, Ridge, Lasso, kNN, and LinearSVR) since we are not sure which would be best suited to our data and feel that trying all and deciding based on R-squared outcomes would be the most effective approach. Furthermore, we did not want to commit to one regression algorithm since it may prove inaccurate or ineffective towards our data. We will use recursive feature elimination (RFE) to choose the most important features as it is hard to tell which features seem to be most directly correlated with the average from looking at the data as stated above. It would also be helpful to compare all of the features to the target using scatterplots to see how many have correlation as this will help us decide how many features we want to choose when running the RFE. For example, if it seems like 5 features might be correlated with the target, we will choose n = 5 for selecting features when running RFE.

<a id="3"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 3. RESULTS

### 3.1. Data Wrangling
In this section, you should do the following and explain why you are doing what you are doing. For each, you should include your code in a cell, followed by a sample output. For instance, if you are one-hot encoding one of your variables, you should first describe what it is and why you are doing it. You should then include your code in a cell, and the sample output should be available as well.

In [5]:
import pandas as pd
hitters = pd.read_csv('https://raw.githubusercontent.com/kevschmitt/Beat-the-Streak/main/hittersByGame.csv')
hitters = hitters[['Hitters', 'AB', 'H', 'Game']]
games = pd.read_csv('https://raw.githubusercontent.com/kevschmitt/Beat-the-Streak/main/games.csv')
games = games[['Game', 'Date']]
hitters.head()

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

        Hitters AB  H       Game
0  M. Carpenter  4  1  360403123
1       T. Pham  1  0  360403123
2      M. Adams  4  0  360403123
3   M. Holliday  3  1  360403123
4    R. Grichuk  4  1  360403123

In [6]:
b_v_p = pd.read_csv('https://raw.githubusercontent.com/kevschmitt/Beat-the-Streak/main/batter_vs_pitcher.csv')
b_v_p

,Unnamed: 0,Name,Team,Opp,Home?,Date,Pitcher,AB,H,XBH,HR,RBI,BB,AVG,OBP,SLG,OPS
0,0,Ian Happ,CHC,MIA,No,3/29/2019,Jose Urena,11,5,3,2,2,1,0.455,0.500,1.091,1.591
1,1,Jonathan Schoop,DET,PIT,Yes,3/29/2019,Ivan Nova,18,6,4,2,3,0,0.333,0.333,0.778,1.111
2,2,Jonathan Villar,NYM,STL,Yes,3/29/2019,Carlos Martinez,30,11,2,1,3,2,0.367,0.406,0.500,0.906
3,3,Nolan Arenado,STL,NYM,No,3/29/2019,Noah Syndergaard,10,4,1,1,1,2,0.400,0.500,0.700,1.200
4,4,Paul DeJong,STL,NYM,No,3/29/2019,Noah Syndergaard,11,6,1,0,0,0,0.545,0.545,0.636,1.182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15759,15759,Carlos Correa,HOU,SEA,No,8/31/2021,Yusei Kikuchi,18,9,3,0,1,1,0.500,0.526,0.722,1.249
15760,15760,Jose Altuve,HOU,SEA,No,8/31/2021,Yusei Kikuchi,20,4,4,1,3,5,0.200,0.370,0.500,0.870
15761,15761,Mookie Betts,LAD,ATL,Yes,8/31/2021,Charlie Morton,24,7,3,1,1,4,0.292,0.414,0.500,0.914
15762,15762,Ty France,SEA,HOU,Yes,8/31/2021,Lance McCullers,12,6,2,0,1,2,0.500,0.571,0.667,1.238
15763,15763,Kyle Seager,SEA,HOU,Yes,8/31/2021,Lance McCullers,48,11,6,3,6,3,0.229,0.275,0.479,0.754

In [7]:
# Reformats the date of a game to the MM/DD/YYYY format so that they are standardized
def format_dates_bvp(date):
    parts = date.split('/')
    ret = ''
    for p in range(0,2):
        if len(parts[p]) == 1:
            ret = ret + '0' + parts[p] + '/'
        else:
            ret = ret + parts[p] + '/'
    ret = ret + parts[2]
    return(ret)

In [8]:
b_v_p['Date'] = b_v_p['Date'].map(format_dates_bvp)

In [9]:
games_stats = pd.merge(hitters, games, on='Game', how='left')

In [10]:
# Reformats the date of a game to the MM/DD/YYYY format
def format_date(date):
    temp = date.split('T')[0]
    parts = temp.split('-')
    return parts[1] + '/' + parts[2] + '/' + parts[0]

In [11]:
# Reformats the names to be the hitter's first initial and last name which simplifies the data
def format_name(name):
    parts = name.split(' ')
    fi = parts[0][:1]
    return fi + '. ' + parts[1]

In [12]:
games_stats['Date'] = games_stats['Date'].map(format_date)
games_stats.head()

        Hitters AB  H       Game        Date
0  M. Carpenter  4  1  360403123  04/03/2016
1       T. Pham  1  0  360403123  04/03/2016
2      M. Adams  4  0  360403123  04/03/2016
3   M. Holliday  3  1  360403123  04/03/2016
4    R. Grichuk  4  1  360403123  04/03/2016

In [13]:
# Changes the name of the "Name" column to "Hitters" to be more specific since there is another player name 
# in the dataframe
b_v_p['Name'] = b_v_p['Name'].map(format_name)
b_v_p = b_v_p.rename(columns = {'Name': 'Hitters'})
b_v_p.head()

,Unnamed: 0,Hitters,Team,Opp,Home?,Date,Pitcher,AB,H,XBH,HR,RBI,BB,AVG,OBP,SLG,OPS
0,0,I. Happ,CHC,MIA,No,03/29/2019,Jose Urena,11,5,3,2,2,1,0.455,0.500,1.091,1.591
1,1,J. Schoop,DET,PIT,Yes,03/29/2019,Ivan Nova,18,6,4,2,3,0,0.333,0.333,0.778,1.111
2,2,J. Villar,NYM,STL,Yes,03/29/2019,Carlos Martinez,30,11,2,1,3,2,0.367,0.406,0.500,0.906
3,3,N. Arenado,STL,NYM,No,03/29/2019,Noah Syndergaard,10,4,1,1,1,2,0.400,0.500,0.700,1.200
4,4,P. DeJong,STL,NYM,No,03/29/2019,Noah Syndergaard,11,6,1,0,0,0,0.545,0.545,0.636,1.182

In [14]:
# Merges the two dataframes above
df = pd.merge(b_v_p, games_stats, on=['Hitters', 'Date'], how='left')

In [15]:
# Used to drop the NaN values in the dataframe
df = df.dropna()
df=df.reset_index()

In [16]:
# Used to rename some of the columns of the dataframe
df = df[['Hitters', 'Pitcher', 'Team', 'Opp', 'Home?', 'Date', 'AB_x', 'H_x', 'XBH', 'HR', 'RBI', 'BB', 'AVG',
               'OBP', 'AB_y', 'H_y']]
df = df.rename(columns = {'Hitters': 'Hitter', 'AB_x': 'ABVP', 'H_x': 'HVP', 'AB_y': 'AB_actual', 'H_y': 'H_actual'})

In [17]:
df['Pitcher'] = df['Pitcher'].map(format_name)

In [18]:
# Used to turn the values in "Home?" column into binary values where 
# 1 = yes and 0 = no so that they can be used in the model
def reformat_home(home):
    if home == 'Yes':
        return 1
    return 0

In [19]:
df['Home?'] = df['Home?'].map(reformat_home)

In [20]:
# Changes all number values in the dataframe to be floats to use in the model
for i in ['ABVP', 'HVP', 'XBH', 'HR', 'RBI', 'BB', 'AVG', 'OBP', 'AB_actual', 'H_actual']:    
    df[i] = df[i].astype(float)
df.head()

,Hitter,Pitcher,Team,Opp,Home?,Date,ABVP,HVP,XBH,HR,RBI,BB,AVG,OBP,AB_actual,H_actual
0,N. Arenado,N. Syndergaard,STL,NYM,0,03/29/2019,10.0,4.0,1.0,1.0,1.0,2.0,0.400,0.500,5.0,2.0
1,A. Bregman,C. Hamels,HOU,TEX,0,03/29/2019,19.0,6.0,3.0,1.0,1.0,1.0,0.316,0.381,4.0,0.0
2,T. Pham,C. Anderson,SD,MIL,1,03/29/2019,14.0,4.0,3.0,2.0,3.0,2.0,0.286,0.375,3.0,1.0
3,Y. Diaz,C. Sale,TB,BOS,1,03/29/2019,12.0,6.0,3.0,0.0,3.0,1.0,0.500,0.538,4.0,2.0
4,T. Story,P. Corbin,COL,ARI,0,03/29/2019,30.0,10.0,7.0,3.0,6.0,6.0,0.333,0.444,4.0,1.0

In [21]:
# Used to create a new column called "Hit?" that has a binary value of whether a hitter got a hit or not 
# (1 = yes, 0 = no)
def float_to_binary(num):
    if (num > 0):
        return 1
    else:
        return 0

In [22]:
df['Hit?'] = df['H_actual'].map(float_to_binary)
df

,Hitter,Pitcher,Team,Opp,Home?,Date,ABVP,HVP,XBH,HR,RBI,BB,AVG,OBP,AB_actual,H_actual,Hit?
0,N. Arenado,N. Syndergaard,STL,NYM,0,03/29/2019,10.0,4.0,1.0,1.0,1.0,2.0,0.400,0.500,5.0,2.0,1
1,A. Bregman,C. Hamels,HOU,TEX,0,03/29/2019,19.0,6.0,3.0,1.0,1.0,1.0,0.316,0.381,4.0,0.0,0
2,T. Pham,C. Anderson,SD,MIL,1,03/29/2019,14.0,4.0,3.0,2.0,3.0,2.0,0.286,0.375,3.0,1.0,1
3,Y. Diaz,C. Sale,TB,BOS,1,03/29/2019,12.0,6.0,3.0,0.0,3.0,1.0,0.500,0.538,4.0,2.0,1
4,T. Story,P. Corbin,COL,ARI,0,03/29/2019,30.0,10.0,7.0,3.0,6.0,6.0,0.333,0.444,4.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11056,C. Correa,Y. Kikuchi,HOU,SEA,0,08/31/2021,18.0,9.0,3.0,0.0,1.0,1.0,0.500,0.526,4.0,1.0,1
11057,J. Altuve,Y. Kikuchi,HOU,SEA,0,08/31/2021,20.0,4.0,4.0,1.0,3.0,5.0,0.200,0.370,5.0,1.0,1
11058,M. Betts,C. Morton,LAD,ATL,1,08/31/2021,24.0,7.0,3.0,1.0,1.0,4.0,0.292,0.414,4.0,1.0,1
11059,T. France,L. McCullers,SEA,HOU,1,08/31/2021,12.0,6.0,2.0,0.0,1.0,2.0,0.500,0.571,4.0,2.0,1
11060,K. Seager,L. McCullers,SEA,HOU,1,08/31/2021,48.0,11.0,6.0,3.0,6.0,3.0,0.229,0.275,3.0,0.0,0

In [23]:
# Features: Home?, ABVP, HVP, XBH, HR, RBI, BB, AVG, OBP
features = df[['Home?', 'ABVP', 'HVP', 'XBH','HR', 'RBI', 'AVG', 'OBP', 'AB_actual']]
features.head()

   Home?  ABVP   HVP  XBH   HR  RBI    AVG    OBP  AB_actual
0      0  10.0   4.0  1.0  1.0  1.0  0.400  0.500        5.0
1      0  19.0   6.0  3.0  1.0  1.0  0.316  0.381        4.0
2      1  14.0   4.0  3.0  2.0  3.0  0.286  0.375        3.0
3      1  12.0   6.0  3.0  0.0  3.0  0.500  0.538        4.0
4      0  30.0  10.0  7.0  3.0  6.0  0.333  0.444        4.0

In [24]:
# Target: Hit?
target = df['Hit?']
target.head()

0    1
1    0
2    1
3    1
4    1
Name: Hit?, dtype: int64

### 3.2. Data Exploration
* Generate appropriate data visualizations for your key variables identified in the previous section
* You should have at least three visualizations (and at least two different visualization types)
* For each visualization provide an explanation regarding the variables involved and an interpretation of the graph. In other words, what does the graph represent?
* Insert your visualizations as images as well (upload the graph images to an online source, e.g. github or imgbb, and embed those into the cells in Jupyter Notebook, similar to HWs). This is a requirement.

### Scatter Matrix of Random Sample of Player Games
This scatter matrix is used to identify any possible relationships between whether **TODO**

<a href="https://imgbb.com/"><img src="https://i.ibb.co/G02KnJk/newplot-2.png" alt="newplot-2" border="0"></a>

<a href="https://imgbb.com/"><img src="https://i.ibb.co/jv7bDP8/newplot-1.png" alt="newplot-1" border="0"></a>

Violin Graph comparing vs pitcher batting averages in players that got a hit vs those who did not

In [30]:
import plotly.express as px
fig = px.violin(df, x='Hit?', y='AVG', color = "Hit?", box=True, template='ggplot2', 
                        points="all", width = 500, violinmode="overlay")

<a href="https://imgbb.com/"><img src="https://i.ibb.co/g7RgzGq/newplot.png" alt="newplot" border="0"></a>

### 3.3. Model Training
* For your machine learning question(s), use the Training, Validation, and Testing approach through GridSearch
* Apply machine learning algorithms (apply at least three different algorithms)
* Train your algorithms using your **training set**

* Evaluate the performance of your algorithms using appropriate evaluation metrics
    * Use at least two different metrics
    * Remember GridSearch will use cross-validation

* Is there any indication of overfitting/underfitting?

* Use one feature selection technique to select a subset of your original features and train your models with the selected features as well (the idea is to see if you can achieve the same using a fewer number of features)

    * **Hint:** You can run your model with all your features and with your selected features, comparing the results (similar to the corresponding HW assignment).

In [31]:
# Split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=3000)

In [32]:
# Classification
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

estimators = {
    'k-Nearest Neighbor': KNeighborsClassifier(), 
    'Support Vector Machine': LinearSVC(max_iter=1000000),
    'Gaussian Naive Bayes': GaussianNB(),
    'Decision Tree': DecisionTreeClassifier()}

for estimator_name, estimator_object in estimators.items():
    kfold = KFold(n_splits=10, random_state=3000, shuffle=True)
    
    scores = cross_val_score(estimator=estimator_object, X=features, y=target, cv=kfold)
    
    print(estimator_name + ": \n\t" + f'mean accuracy={scores.mean():.2%}, ' 
          + f'standard deviation={scores.std():.2%}' +"\n")

k-Nearest Neighbor:
	mean accuracy=69.03%, standard deviation=0.89%

Support Vector Machine:
	mean accuracy=73.33%, standard deviation=1.15%

Gaussian Naive Bayes:
	mean accuracy=73.21%, standard deviation=1.17%

Decision Tree:
	mean accuracy=66.97%, standard deviation=1.31%

In [34]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import MinMaxScaler

param_grid = {'multi_class': ['ovr', 'crammer_singer'], 'loss': ['hinge', 'squared_hinge']}
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=3000)
    
scaler = MinMaxScaler()
scaler.fit(X_train) 
X_train_scaled = scaler.transform(X_train) 
X_test_scaled = scaler.transform(X_test) 

from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(LinearSVC(max_iter=1000000), param_grid)

grid_search.fit(X=X_train, y=y_train)

# result of grid search
print("Best estimator: ", grid_search.best_estimator_)
print("Best parameters: ", grid_search.best_params_)
print("Best cross-validation score: ", grid_search.best_score_)

Best estimator:  LinearSVC(max_iter=1000000, multi_class='crammer_singer')
Best parameters:  {'loss': 'squared_hinge', 'multi_class': 'crammer_singer'}
Best cross-validation score:  0.7306811332127788

In [47]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import MinMaxScaler

# Testing if scaled data outperforms original data    
scaler = MinMaxScaler()
scaler.fit(X_train) 
X_train_scaled = scaler.transform(X_train) 
X_test_scaled = scaler.transform(X_test) 

# Creating scaled features dataframe from X_train and X_test scaled data
features_scaled = pd.DataFrame(columns = features.columns, data=X_train_scaled)
temp = pd.DataFrame(columns = features.columns, data=X_test_scaled)
features_scaled = features_scaled.append(temp)

for x in [features, features_scaled]:
    kfold = KFold(n_splits=10, random_state=3000, shuffle=True)
    
    scores = cross_val_score(estimator=LinearSVC(max_iter=1000000, multi_class='crammer_singer'),
                             X=x, y=target, cv=kfold)
    
    print(estimator_name + ": \n\t" + f'mean accuracy={scores.mean():.2%}, ' 
          + f'standard deviation={scores.std():.2%}' +"\n")

Decision Tree:
	mean accuracy=73.22%, standard deviation=1.00%

Decision Tree:
	mean accuracy=68.73%, standard deviation=0.65%

Non-scaled data gave more accurate results

### 3.4. Model Optimization
* Tune your models using hyperparameters appropriate for your algorithms
* Explain why you are doing this (e.g., to avoid overfitting, etc.)

In [ ]:
# hyperparameters to be changed are 
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=3000)
model = LinearSVC(max_iter=1000000, multi_class = )

### 3.5. Model Testing
* Test your tuned algorithms using your **testing set**

<a id="4"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 4. DISCUSSION
* Interpret your findings from 3.3, 3.4, and 3.5
    * Which algorithms did you compare?
    * Which algorithm(s) revealed best performance? With what parameters?
    * Which algorithm(s) should be used for your predictive model?
    * Based on your findings, can we use the features in your dataset to predict the outcome variable you identified using the algorithms you've applied? (It is okay if the answer is no. We're interested in the process, not the performance of the model.)

* Discuss the ethical implications of your project. Should your results be accepted at face value, why or why not? (e.g. any dataset bias or methodological issues?)

* End this section with a conclusion paragraph containing some pointers for future work
    * (e.g., get more data/features, perform another analysis, etc.)

<a id="5"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

### CONTRIBUTIONS
* Describe each team member's contributions to the report (who did what in each section)
* Remember this is a team effort!
* Each member of your team will later provide peer evaluation of other team members. Your final grade on the project will be based on those peer evaluations. A survey will be shared after the deadline for this deliverable.